services:
  app-server:
    build:
      context: .
    container_name: "telemetry-app-server"
    restart: always
    environment:
      NODE_ENV: ${NODE_ENV}
      PG_DATABASE: ${PG_DATABASE}
      PG_USERNAME: ${PG_USERNAME}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_PORT: ${PG_PORT}
      PG_HOST: ${PG_HOST}
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_DATABASE_NAME: ${MONGODB_DATABASE_NAME}
      MONGODB_HOST: ${MONGODB_HOST}
      MONGODB_PORT: ${MONGODB_PORT}
      MONGODB_RULES_COLLECTION: ${MONGODB_RULES_COLLECTION}
      PORT: ${PORT}
    ports:
      - 3002:${PORT}
    depends_on:
      - postgresdb
      - mongo
  postgresdb:
    image: postgres
    container_name: telemetry-app-postgres
    restart: always
    environment:
      POSTGRES_USER: ${PG_ROOT_USER}
      POSTGRES_PASSWORD: ${PG_ROOT_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./postgres-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_ROOT_USER} -d ${PG_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo
    container_name: telemetry-app-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
  mongo_data:
